# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b85b55b94e826c378b679eddaf524083b16429e013f9eca6153c80f456c67d7500e242855ccb28fa9e8b16988e96699519e32a14ad5da705a957b4a3d60e044

test:
  secret_key_base: 691191de1183ae7953e7efa4fd946ed368c3dcdb7ba28e21a6bc384db623a36c5cc5de996a4a703e096f10536946d9c407029d1772dbfbb728f4138accff6f98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
